version: "3"

services:
  takeout_app:
    container_name: takeout_app
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - takeout-net

networks:
  takeout-net:
    driver: bridge